version: 2
jobs:
    python-3.4: &build
        docker:
            - image: circleci/jdk8:0.1.1

        steps:
            - checkout
            - restore_cache:
                key: coala-bears-dep-{{checksum "requirements.txt"}}

            - run:
                name: dependencies
                command: |
                  sudo apt-get update
                  sudo apt-get install -y software-properties-common python-software-properties curl git
                  curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash  -
                  curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
                  echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
                  sudo apt-get update
                  sudo apt-get install python3.4-venv libcurl4-openssl-dev make

            - run:
                name: virtual-env
                command: |
                  if [ ! -d "$HOME/.venv" ]; then
                  python3 -m venv ~/.venv
                  fi
                  echo 'source $HOME/.venv/bin/activate' >> $BASH_ENV

            - run:
                name: pre
                command: |
                  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
                  echo 'export NVM_DIR=$HOME/.nvm' >> $BASH_ENV
                  export NVM_DIR=$HOME/.nvm
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  nvm install 6.10.2
                  nvm alias default node
                  echo 'source $NVM_DIR/nvm.sh' >> $BASH_ENV
                  echo 'export PATH=$HOME/elm-format-0.18:$PATH' >> $BASH_ENV
                  echo 'export PATH=$HOME/project/node_modules/.bin:$PATH' >> $BASH_ENV

            - run:
                name: generalDependencies
                command: |
                  bash .ci/deps.sh

            - run:
                name: dependenciesPip
                command: |
                  git clone https://github.com/pyenv/pyenv.git /tmp/pyenv
                  mkdir -p ~/.pyenv
                  cp -R /tmp/pyenv/* ~/.pyenv
                  echo 'export PYENV_ROOT=$HOME/.pyenv' >> $BASH_ENV
                  echo 'export PATH=$PYENV_ROOT/bin:$PATH' >> $BASH_ENV
                  source $BASH_ENV
                  eval "$(pyenv init -)"
                  bash .ci/deps.pip.sh

            - run:
                name: setup
                when: always
                command: python setup.py bdist_wheel

            - run:
                name: allDependencies
                when: always
                command: pip install $(ls ./dist/*.whl)"[alldeps]"

            - run:
                name: tests
                when: always
                command: bash .ci/tests.sh

workflows:
    version: 2
    test:
        jobs:
            - python-3.4
